dist: trusty
language: python
python:
- '3.6'
stages:
  - compile
  - test
  - name: deploy
    if: branch = master
jobs:
  include:
    - stage: compile
      script:
      - echo "compileing?"
    - stage: test
      script:
      - echo "Testing"
    - script: echo "OVERIDE ???"
