dist: trusty
language: python
stages:
  #- compile
  #- test
  - name: deploy
    if: branch = master
env:
  - distro=alpine
  - distro=ubuntu

script:
  - echo ${distro}
jobs:
  include:
    - stage: deploy
      script:
        - echo 'warming up'
        - echo "compileing?"
