dist: trusty
language: python
stages:
  - compile
  - test
  - name: deploy
    if: branch = master
env:
  - distro=alpine
  - distro=ubuntu
jobs:
  include:
    - stage: compile
      script:
      - echo 'warming up'
      - echo "compileing?"
    - script: echo "Ordered dict???"
    - stage: test
      script:
      - echo "Testing"
